DROP TABLE IF EXISTS `blogcomments`;
CREATE TABLE blogcomments ( comments_id INTEGER  NOT NULL PRIMARY KEY, title VARCHAR(120) NOT NULL, comment VARCHAR(255) NOT NULL, email VARCHAR(120) NULL, approval_status INTEGER NOT NULL, entry_id INTEGER NOT NULL, modified INTEGER NOT NULL);
INSERT INTO `blogcomments` VALUES(1,'A PHP Prerequisite','The course that every PHP developer should take','kevin@zend.com',1,5,1196097666);
INSERT INTO `blogcomments` VALUES(2,'test','A comment','kevin@zend.com',1,1,1262718259);
INSERT INTO `blogcomments` VALUES(3,'test','A comment','kevin@zend.com',1,1,1262718263);
INSERT INTO `blogcomments` VALUES(4,'test','A comment','kevin@zend.com',1,1,1262720213);
INSERT INTO `blogcomments` VALUES(5,'Cloud Test','Cloud Test','doug@unlikelysource.com',0,5,1331151553);
DROP TABLE IF EXISTS `blogentries`;
CREATE TABLE blogentries ( entry_id INTEGER  NOT NULL PRIMARY KEY, title VARCHAR(120) NOT NULL, content TEXT NULL, modified INTEGER NULL);
INSERT INTO `blogentries` VALUES(1,'Zend Training - Higher Structures','The Zend Higher Structures of PHP course is designed to expand a beginning programmers understanding of the PHP language. This intermediate-level course builds upon knowledge gained in the Foundations of PHP class, and utilizes a hands-on approach with numerous examples and practical exercises to enhance learning. By the end of the course, you will have completed a functioning e-commerce program while you learn the essentials for creating web-based PHP applications. You will also have the opportunity to use the Zend Studio IDE (Integrated Development Environment) to continue honing your coding skills utilizing best practices and effective tools.

This course continues where Foundations of PHP leaves off, and is designed for novice PHP developers who want to further advance their skills in the PHP language and already know the basics of PHP syntax, language constructs, and web site functionality. Experienced programmers in Procedural and OO languages should refer to the Quick Start: PHP for Experienced Programmers course description. ILE programmers are coached to complete the Foundations of PHP and Higher Structures of PHP courses, as the language syntax they are used to is unique and quite different from PHP.',1196096929);
INSERT INTO `blogentries` VALUES(2,'Zend Training - Foundations of PHP','The Foundations of PHP course is designed to provide non-programmers with a solid foundation in the PHP language. This Course guides you through the basics of PHP with an experiential approach, filled with numerous examples and hands-on exercises. By the end of the course, you will have completed a functioning Blackjack program while you learn the essentials you need to program in PHP. You will also have the opportunity to use the Zend Studio IDE (Integrated Development Environment) to start your coding adventures the easy and correct way!

This course is designed for those who want to learn the basics of the PHP language and assumes some familiarity with websites  what they are and the very basics of how they work  but no programming experience. Web designers who want to become PHP Developers would certainly benefit from this course. This course could also be appropriate for those programmers who have limited exposure to other languages, and want to now learn PHP.',1196096999);
INSERT INTO `blogentries` VALUES(3,'Zend Training - Certification','The Zend PHP 5 Certification course prepares experienced PHP programmers for the challenge of passing the PHP certification exam and achieving the status of Zend Certified Engineer (ZCE).

This is a test preparation and PHP review course  it does not teach PHP. The content discusses important information about the exam itself and strategies for answering the exam questions, in addition to providing an in-depth review of the twelve certification topic areas. Participants are continually challenged to test their knowledge with focused quizzes. The course moves at a fast pace, and assumes at least an intermediate skill level in programming within PHP. 

This course is designed for experienced PHP developers (intermediate-level +) who wish to gain information on how to take and pass the PHP 5 Certification exam while being guided through a quick, intense review of all of the major topics within the 12 certification areas.',1196097304);
INSERT INTO `blogentries` VALUES(4,'Zend Training - PHP for Experienced Programmers','The Zend Quick Start: PHP for Experienced Programmers course is designed to quickly build an experienced programmers understanding of the PHP language. This course covers many of the same topics as both the Foundations of PHP and Higher Structures of PHP classes but at an accelerated rate with special emphasis on the differences between PHP and other commonly used languages. As with the other classes, it utilizes a hands-on approach with numerous examples and practical exercises to enhance learning. By the end of the course, you will complete a functioning program while you learn the essentials for creating web-based PHP applications. You will also have the opportunity to use the Zend Studio IDE (Integrated Development Environment) to continue honing your coding skills utilizing best practices and effective tools.

This course is designed for experienced developers (2+ years) of other languages - Procedural & OO, such as C, Java, C++, C#, JavaScript, Python, Perl, Ruby - who want to transfer their skills to PHP and need to quickly learn the PHP-specific version of common features, such as syntax and language constructs. (For ILE programmers without experience in these other programming families, we recommend taking the Foundations of PHP & Higher Structures of PHP courses.)',1196097423);
INSERT INTO `blogentries` VALUES(5,'Zend Training - Building Security into your PHP Applications','Security is one of the most important things to keep in mind when developing web applications. Unfortunately, it is also one of the things most easy to overlook. Reviewing hundreds or thousands of lines of code may be a daunting task, but it is one that can be avoided if an application is developed with security in mind.

This PHP class presents a comprehensive overview of security and has been designed to equip PHP developers with the knowledge they need to build more secure web applications. 

This course is designed for experienced PHP application developers who want to learn or be reminded of security best practices. It is also appropriate for new PHP developers who want to learn how to build security into the applications they are learning to create.',1196097463);
DROP TABLE IF EXISTS `blogusers`;
CREATE TABLE blogusers ( user_id INTEGER  NOT NULL PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(32) NULL, real_name VARCHAR(150) NULL, ppi VARCHAR(80));
INSERT INTO `blogusers` VALUES(1,'administrator','password','Administrator',NULL);
