version: "3"
services:
  class_php_examples:
    container_name: classic_php_examples
    hostname: classic-php-examples
    image: class_php_examples/class_php_examples_latest
    volumes:
     - .:/repo
    ports:
     - 8181:80
     - 9501:9501
    build: ./docker
    restart: always
    command: /tmp/startup.sh
    networks:
      app_net:
        ipv4_address: 172.16.8.81

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.8.0/24"
