<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- Other files: multi_page_form.php, page2.phtml, page3.phtml -->
<head>
	<title>Multi Page Form</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="generator" content="Geany 0.16" />
</head>

<body bgcolor="#EB6262">
<h1>Page 1</h1>	
<hr />
<form action="multi_page_form.php" method="POST">
<table border=0>
	<tr>
		<th>Name</th>
		<td><input type="text" size=40 maxlength=255 name="item[1][1]" value="<?php echo @$item[1][1]; ?>" /></td>
	</tr>
	<tr>
		<th>Address</th>
		<td><textarea name="item[1][2]" rows=4 cols=40><?php echo @$item[1][2]; ?></textarea></td>
	</tr>
</table>
<table>
	<tr>
		<td><input type='submit' name='page1' value='Page 1' /></td>
		<td><input type='submit' name='page2' value='Page 2' /></td>
		<td><input type='submit' name='page3' value='Page 3' /></td>
	</tr>
</table>
<input type="hidden" name="page" value="1" />
</form>
</body>
</html>
